version: '3'

services:
  # test:
  #   image: alpine
  #   ports:
  #     - 2323:2323
  #   stdin_open: true
  #   tty: true
  hanami:
    build: .
    # command: bundle exec hanami server --host=0.0.0.0
    environment:
      DATABASE_HOST: db
      DATABASE_USER_NAME: root
      DATABASE_PASSWORD: pass
      DATABASE_URL: 'mysql2://root:pass@db:3306/hanami_study_development'
      WEB_SESSIONS_SECRET: xxx
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      # exclude volumes
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    depends_on:
      - db
    ports:
      - ${PORT:-2300}:2300
    stdin_open: true
    tty: true

  db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  bundle:
